# -------------------------------------------------------------------------------------------------
# This workflow deploys the documentation site on GitHub Pages.
# The site is accessible on https://{{repo_owner}}.github.io/{{repo_name}}
# -------------------------------------------------------------------------------------------------
---
name: deploy-docs

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "/docs/**"
      - "/.vitepress/**"

jobs:
  deploy:
    name: Deploy documentation site
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: generate_token
        # yamllint disable-line rule:line-length
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permissions: contents:write
          # Uncomment if the app is installed at the organization level
          # organization: ${{ github.repository_owner }}

      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Configure Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy documentation site
        run: make docs-deploy
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
