# --------------------------------------------------------
# This workflow checks for leaked credentials
# --------------------------------------------------------
---
name: leaked-secrets

on: 
  pull_request_target:
  workflow_dispatch:
  push:

jobs:
  scan:
    name: Scan for leaked secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        # There is no need to pin the action to a commit SHA as long as:
        # - The action is in the same repo as TruffleHog
        # - The image used in the action is 'latest' and is not configurable
        #
        # => If a malicious commit is introduced in the repo, both the action
        # and the image would be compromised.
        uses: trufflesecurity/trufflehog@v3.6.1
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
